# Generated by Django 4.2 on 2023-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_profile_usename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='C:\\Users\\DELL\\devworkspace\\projects\\school_app\\virtual\\School-App\\backend\\static/images/user_photo.png', null=True, upload_to=''),
        ),
    ]
