# Generated by Django 4.2 on 2023-04-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usename',
            new_name='username',
        ),
    ]
