# Generated by Django 4.2 on 2023-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_usename_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://eu-central-1.linodeobjects.com/media//user_photo.png', null=True, upload_to=''),
        ),
    ]
