# Generated by Django 4.2 on 2023-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='C:\\Users\\DELL\\devworkspace\\projects\\school_app\\virtual\\School-App\\backend\\media/user_photo.png', null=True, upload_to=''),
        ),
    ]
